name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]
  # ปิด pull_request ไปก่อน ถ้า PR มาจาก fork จะไม่มี secrets
  # pull_request:
  #   branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (event-frontend/Dockerfile)
        uses: docker/build-push-action@v5
        with:
          context: ./event-frontend
          file: ./event-frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/event-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/event-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
