name: Build & Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Detect Dockerfile & context แบบอัตโนมัติ
      - name: Detect Dockerfile path
        id: detect
        run: |
          set -e
          echo "== repo tree =="
          ls -la
          echo "== try common dirs =="
          ls -la event-frontend || true
          ls -la frontend || true
          ls -la app || true

          CANDS=( "./Dockerfile" "./event-frontend/Dockerfile" "./frontend/Dockerfile" "./app/Dockerfile" )
          FOUND=""
          for p in "${CANDS[@]}"; do
            if [ -f "$p" ]; then FOUND="$p"; break; fi
          done
          if [ -z "$FOUND" ]; then
            echo "❌ Not found Dockerfile in ./, ./event-frontend, ./frontend, ./app"
            exit 1
          fi
          CONTEXT="$(dirname "$FOUND")"
          echo "FOUND=$FOUND"
          echo "CONTEXT=$CONTEXT"
          echo "file=$FOUND" >> $GITHUB_OUTPUT
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.detect.outputs.context }}
          file: ${{ steps.detect.outputs.file }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/event-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/event-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
